# Generated by Django 3.2.4 on 2021-06-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=5)),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('copies', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('isLibrarian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Submitted_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bookname', models.CharField(default='empty', max_length=100)),
                ('amountpaid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_bookid', to='users.books')),
                ('libid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_librarian_id', to='users.library_users')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_student_id', to='users.library_users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transactionid', models.CharField(max_length=50)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_bookid', to='users.books')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_student_id', to='users.library_users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transactionstatus', models.CharField(max_length=50)),
                ('transactionid', models.CharField(max_length=50)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymenthistory_bookid', to='users.books')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymenthistory_student_id', to='users.library_users')),
            ],
        ),
        migrations.CreateModel(
            name='Issued_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bookname', models.CharField(default='empty', max_length=100)),
                ('duedate', models.DateField()),
                ('amountdue', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_bookid', to='users.books')),
                ('libid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_librarian_id', to='users.library_users')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_student_id', to='users.library_users')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bookname', models.CharField(default='empty', max_length=100)),
                ('ttype', models.CharField(max_length=10)),
                ('copies', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_bookid', to='users.books')),
                ('libid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_librarian_id', to='users.library_users')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_student_id', to='users.library_users')),
            ],
        ),
    ]
